Repository second-hand-team-04/second-hand-max-fe, pull requests merged in 2023-09, with the labels that each got.

#52 고정 MockData 삭제 및 쿼리 적용
  src/api/category/index.ts
  src/api/category/types.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useRegionsQuery.tsx
  src/api/queries/useUser.ts
  src/api/region/index.ts
  src/api/types.ts
  src/api/user/index.ts
  src/api/user/types.ts
  src/components/Category/CategoryButton.tsx
  src/components/Category/CategoryItem.tsx
  src/components/Category/CategoryModal.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/common/Modal/ModalStyles.ts
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/CategoryPage.tsx
  src/pages/NewProductPage.tsx
  src/router/ProtectedRoute.tsx
  src/router/PublicOnlyRoute.tsx
  src/utils/useCategory.tsx
Labels: feat, refactor

#55 PR 리뷰 피드백에 대한 수정
  package-lock.json
  package.json
  src/api/category/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useCategoriesQuery.ts
  src/api/queries/useRegionsQuery.ts
  src/api/region/index.ts
  src/api/user/index.ts
  src/components/Category/CategoryModal.tsx
  src/pages/CategoryPage.tsx
  src/pages/NewProductPage.tsx
  src/utils/useCategory.tsx
Labels: refactor

#56 NewProductPage 텍스트관련 Hooks 적용
  src/hooks/useText.tsx
  src/pages/NewProductPage.tsx
  src/pages/SignUpPage.tsx
  src/utils/priceFormatter.ts
Labels: refactor

#57 SignInPage 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/fetcher/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useSignInMutation.ts
  src/api/queries/useSignUpMutation.ts
  src/api/types.ts
  src/api/user/index.ts
  src/components/CustomToaster.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarTab.tsx
  src/components/common/Button/ButtonVariants.tsx
  src/components/common/TextInput/TextInput.tsx
  src/hooks/useText.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/NewProductPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/router/router.tsx
  src/styles/designSystem.ts
Labels: feat, design, refactor

#59 Home Page구현 및 Region Modal 연결
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useProductItemsQuery.ts
  src/api/queries/useRegionsQuery.ts
  src/api/region/index.ts
  src/api/user/index.ts
  src/components/Category/CategoryModal.tsx
  src/components/Home/FabButton.tsx
  src/components/Home/ProductItem.tsx
  src/components/NavBar/NavBar.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/SelectInput/SelectInput.tsx
  src/components/common/SelectInput/SelectItem.tsx
  src/components/common/SelectInput/selectInputProps.ts
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/HomePage.tsx
  src/pages/NewProductPage.tsx
  src/router/router.tsx
  src/utils/stringFormatters.ts
Labels: feat, design, refactor

#62 Auth 구현
  src/App.tsx
  src/api/fetcher/index.ts
  src/api/queries/useOAuthSignInMutation.ts
  src/api/queries/useUserQuery.ts
  src/api/user/index.ts
  src/assets/images/default-profile-image.jpg
  src/assets/images/kakao_bubble_icon.png
  src/components/CustomToaster.tsx
  src/components/KakaoSignInButton.tsx
  src/context/WindowContext.tsx
  src/main.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/router/ProtectedRoute.tsx
  src/router/PublicOnlyRoute.tsx
  src/router/router.tsx
  src/styles/designSystem.ts
  src/utils/openPopUpWindow.ts
  src/utils/textValidators.ts
  tsconfig.json
Labels: feat, design, refactor

#61 Profile 페이지 구현
  src/App.tsx
  src/api/queries/useSignOutMutation.ts
  src/api/queries/useUserInfoQuery.ts
  src/components/NavBar/NavBar.tsx
  src/mocks/data.ts
  src/pages/MyProfilePage.tsx
  src/pages/SignInPage.tsx
  src/router/router.tsx
Labels: feat, design

#65 fix: Signup endpoint 수정
  src/api/user/index.ts
Labels: fix

#67 3주차 배포4
  src/api/user/index.ts
  src/pages/SignUpPage.tsx
Labels: fix, merge

#69 3주차 배포5
  src/pages/SignInPage.tsx
  src/router/ProtectedRoute.tsx
  src/router/router.tsx
Labels: merge

#74 FallbackPage 구현
  src/api/user/index.ts
  src/assets/images/logo.jpeg
  src/pages/FallbackPage.tsx
  src/router/router.tsx
  src/styles/designSystem.ts
Labels: feat, design

#77 3주차 배포8
  src/api/queries/useOAuthSignInMutation.ts
  src/api/queries/useSignInMutation.ts
  src/pages/SignInPage.tsx
Labels: merge

#84 useOutsideClick 구현 및 적용
  src/api/region/index.ts
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/SelectInput/SelectInput.tsx
  src/hooks/useOutsideClick.tsx
Labels: feat

#85 프로필 닉네임,이미지 수정 기능 구현
  src/App.tsx
  src/api/queries/queryKeys.ts
  src/api/queries/useProfileMutation.ts
  src/api/queries/useUserInfoQuery.ts
  src/api/user/index.ts
  src/hooks/useText.tsx
  src/pages/MyProfilePage.tsx
Labels: feat, design

#81 3주차 PR 리뷰 피드백에 대한 수정사항
  src/App.tsx
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useAllRegionsQuery.ts
  src/api/queries/useProductItemsInfiniteQuery.ts
  src/api/queries/useProductItemsQuery.ts
  src/api/queries/useRegionsQuery.ts
  src/api/queries/useUserRegionsQuery.ts
  src/api/region/index.ts
  src/assets/icon/heart-filled.svg
  src/assets/icon/heart.svg
  src/assets/icon/message.svg
  src/components/Category/CategoryButton.tsx
  src/components/Home/ProductItem.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/components/common/InfiniteScroll/InfiniteScrollList.tsx
  src/components/common/SelectInput/useSelectInput.tsx
  src/context/ProductItemsFiltersContext.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/CategoryPage.tsx
  src/pages/HomePage.tsx
  src/router/router.tsx
Labels: refactor

#86 Auth 관려 Refactor
  .gitignore
  .vscode/settings.json
  src/App.tsx
  src/api/fetcher/index.ts
  src/api/queries/useAllRegionsQuery.ts
  src/api/queries/useOAuthSignInMutation.ts
  src/api/queries/useProductItemsInfiniteQuery.ts
  src/api/queries/useProfileMutation.ts
  src/api/queries/useSignInMutation.ts
  src/api/queries/useSignOutMutation.ts
  src/api/queries/useSignUpMutation.ts
  src/api/queries/useUserInfoQuery.ts
  src/api/queries/useUserRegionsQuery.ts
  src/components/Category/CategoryItem.tsx
  src/components/Home/FabButton.tsx
  src/components/Home/ProductItem.tsx
  src/components/KakaoSignInButton.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarTab.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/components/common/Alert/Alert.tsx
  src/components/common/Alert/AlertStyles.ts
  src/components/common/Button/Button.tsx
  src/components/common/Button/ButtonVariants.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/SelectInput/SelectInput.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/CategoryPage.tsx
  src/pages/FallbackPage.tsx
  src/pages/HomePage.tsx
  src/pages/MyProfilePage.tsx
  src/pages/NewProductPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/router/ProtectedRoute.tsx
  src/router/PublicOnlyRoute.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: refactor

#87 Product 수정 기능 구현
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useProductItemDetailsQuery.ts
  src/api/queries/useProductItemEditMutation.ts
  src/api/queries/useProductItemMutation.ts
  src/api/queries/useProductItemsInfiniteQuery.ts
  src/api/queries/useUserInfoMutation.ts
  src/api/region/index.ts
  src/components/Category/CategoryModal.tsx
  src/components/Product/ProductItem.tsx
  src/hooks/useOutsideClick.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/EditProductItemPage.tsx
  src/pages/HomePage.tsx
  src/pages/MyProfilePage.tsx
  src/pages/NewProductItemPage.tsx
  src/pages/ProductItemPage.tsx
  src/router/router.tsx
  src/utils/stringFormatters.ts
  src/utils/useRandomCategories.tsx
Labels: feat, design

#89 MyTransactionsPage 구현
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useProductItemStatusEditMutation.ts
  src/api/queries/useTransactionsInfiniteQuery.ts
  src/api/region/index.ts
  src/api/transactions/index.ts
  src/api/user/index.ts
  src/api/wishlist/index.ts
  src/assets/icon/heart.svg
  src/assets/icon/message.svg
  src/components/AppBar.tsx
  src/components/Product/ProductItem.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/Tag/Tag.tsx
  src/hooks/useIntersection.tsx
  src/hooks/useOutsideClick.tsx
  src/mocks/data.ts
  src/mocks/handlers.ts
  src/pages/HomePage.tsx
  src/pages/MyTransactionsPage.tsx
  src/pages/NewProductItemPage.tsx
  src/router/Routes.ts
  src/router/router.tsx
Labels: feat, design, refactor

#90 feat: 상품 삭제 기능 구현
  src/api/queries/queryKeys.ts
  src/api/queries/useProductItemDeleteMutation.ts
  src/components/Region/RegionSelectModal.tsx
  src/components/common/Alert/Alert.tsx
  src/pages/EditProductItemPage.tsx
  src/pages/ProductItemPage.tsx
  src/utils/objectDifferences.ts
Labels: feat, design, refactor

#92 #88 feat: 나의 동네 선택 API 연결
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useAllRegionsQuery.ts
  src/api/queries/useUserRegionMutation.ts
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/mocks/handlers.ts
  src/pages/ProductItemPage.tsx
Labels: feat

#94 4주차 배포2
  src/api/queries/useUserRegionsQuery.ts
  src/components/Region/RegionAddModal.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/pages/EditProductItemPage.tsx
Labels: fix, merge

#95 4주차 배포3
  src/api/region/index.ts
Labels: fix, merge

#96 4주차 배포3
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useImageUploadMutation.ts
  src/components/Category/CategoryButton.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/context/ProductItemsFiltersContext.tsx
  src/pages/HomePage.tsx
  src/pages/MyProfilePage.tsx
  src/pages/NewProductItemPage.tsx
Labels: fix, merge

#97 4주차 배포5
  src/pages/EditProductItemPage.tsx
Labels: fix, merge

#99 4주차 배포7
  src/assets/images/logo.jpeg
  src/assets/images/logo.png
  src/components/AppBar.tsx
  src/components/Product/ProductItem.tsx
  src/pages/FallbackPage.tsx
  src/pages/HomePage.tsx
  src/pages/NewProductItemPage.tsx
  src/pages/ProductItemPage.tsx
  src/utils/time.ts
Labels: fix, merge

#100 W4 작업 W5로 이동
  README.md
  src/api/queries/useUserInfoQuery.ts
  src/api/queries/useUserRegionsQuery.ts
  src/api/user/index.ts
  src/components/KakaoSignInButton.tsx
  src/components/Product/ProductItem.tsx
  src/config/index.ts
  src/main.tsx
  src/pages/SignInPage.tsx
Labels: merge, refactor

#101 MyWishlistPage 구현
  src/api/productItem/index.ts
  src/api/queries/queryKeys.ts
  src/api/queries/useProductItemDeleteMutation.ts
  src/api/queries/useWishlistItemAddMutation.ts
  src/api/queries/useWishlistItemRemoveMutation.ts
  src/api/queries/useWishlistItemsInfiniteQuery.ts
  src/api/wishlist/index.ts
  src/context/ProductItemsFiltersContext.tsx
  src/mocks/data/productItemData.ts
  src/mocks/data/userData.ts
  src/pages/MyTransactionsPage.tsx
  src/pages/MyWishlistPage.tsx
  src/pages/ProductItemPage.tsx
  src/router/router.tsx
Labels: feat, design, refactor

#102 관심목록 상품 카테고리 API 분리
  src/api/queries/queryKeys.ts
  src/api/queries/useWishlistItemsCategoriesQuery.ts
  src/api/wishlist/index.ts
  src/pages/MyWishlistPage.tsx
  src/pages/ProductItemPage.tsx
Labels: feat, refactor

#104 상품 상세 조회 이미지 Carousel 구현
  package-lock.json
  package.json
  src/components/common/DraggableImageSlider/DraggableImageSlider.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/pages/ProductItemPage.tsx
  src/styles/constants/zIndex.ts
Labels: feat, design

#106 5주차 배포2
  src/components/common/DraggableImageSlider/DraggableImageSlider.tsx
  src/components/common/Tag/Tag.tsx
  src/pages/MyWishlistPage.tsx
  src/pages/NewProductItemPage.tsx
Labels: fix

#107 5주차 배포3
  src/App.tsx
  src/api/queries/useProductItemStatusEditMutation.ts
  src/components/Product/ProductItem.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/hooks/useIntersection.tsx
  src/pages/HomePage.tsx
  src/pages/MyTransactionsPage.tsx
  src/pages/MyWishlistPage.tsx
  src/pages/NewProductItemPage.tsx
  src/pages/ProductItemPage.tsx
Labels: merge
