Repository second-hand-team-04/second-hand-max-fe, pull requests merged in 2023-08, with the labels that each got.

#5 SelectInput Component 구현
  README.md
  src/components/common/SelectInput/SelectInput.tsx
  src/components/common/SelectInput/SelectItem.tsx
  src/components/common/SelectInput/index.ts
  src/components/common/SelectInput/selectInputProps.ts
  src/components/common/SelectInput/useSelectInput.tsx
  src/styles/designSystem.ts
Labels: feat

#9 Dropdown 컴포넌트 구현
  README.md
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/Dropdown/index.ts
  src/components/common/hooks/useViewportIntersection.tsx
Labels: feat, design

#13 MSW 초기화
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browserServiceWorker.ts
  src/mocks/data.ts
  src/mocks/handlers.ts
Labels: chore

#7 Modal Component 구현
  src/components/Category/CategoryItem.tsx
  src/components/Category/CategoryModal.tsx
  src/components/Region/RegionAddModal.tsx
  src/components/Region/RegionItem.tsx
  src/components/Region/RegionModal.tsx
  src/components/Region/RegionSelectModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ModalStyles.ts
  src/components/common/Modal/index.ts
Labels: feat, design

#15 Axios 초기화
  .gitignore
  src/api/fetcher/index.ts
Labels: chore

#18 Tag Component 구현
  src/App.tsx
  src/components/common/Tag/Tag.tsx
Labels: feat, design

#19 Alert Component 구현
  src/components/common/Alert/Alert.tsx
  src/components/common/Alert/AlertStyles.ts
  src/components/common/Alert/index.ts
Labels: feat, design

#21 Button 컴포넌트 구현
  src/components/common/Button/Button.tsx
  src/components/common/Button/ButtonVariants.tsx
  src/components/common/Button/index.ts
  src/components/common/Button/types.ts
  src/components/common/types.ts
Labels: feat, design

#25 React Query 설정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
Labels: chore

#22 NavBar 컴포넌트 구현
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavBarTab.tsx
  src/components/common/Button/ButtonVariants.tsx
  src/styles/designSystem.ts
Labels: feat, design

#27 Header 컴포넌트 구현
  src/components/Header.tsx
  src/styles/designSystem.ts
Labels: feat, design

#23 CategoryButton 컴포넌트 구현
  src/components/Category/CategoryButton.tsx
Labels: feat, design

#32 Category 페이지 구현
  src/components/Category/CategoryButton.tsx
  src/components/Header.tsx
  src/pages/CategoryPage.tsx
Labels: feat, design

#33 Router 및 React Query init
  src/App.css
  src/App.tsx
  src/api/queries/queryKeys.ts
  src/api/queries/useUser.ts
  src/api/user/index.ts
  src/api/user/types.ts
  src/mocks/handlers.ts
  src/pages/Root.tsx
  src/router/ProtectedRoute.tsx
  src/router/PublicOnlyRoute.tsx
  src/router/router.tsx
Labels: chore

#38 AppBar 공유를 위한 중간 PR
  src/App.tsx
  src/components/AppBar.tsx
  src/components/common/SelectInput/SelectInput.tsx
  src/index.css
  src/main.tsx
  src/pages/CategoryPage.tsx
  src/pages/Root.tsx
  src/router/router.tsx
Labels: design

#40 AppBar 컴포넌트 구현
  src/components/AppBar.tsx
Labels: feat, design

#42 NewProduct 페이지 구현
  src/components/AppBar.tsx
  src/components/Category/CategoryButton.tsx
  src/components/Category/CategoryItem.tsx
  src/components/Category/CategoryModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Tag/Tag.tsx
  src/hooks/useDraggable.tsx
  src/pages/NewProductPage.tsx
  src/styles/designSystem.ts
  src/utils/useCategory.tsx
Labels: feat, design, refactor, style

#44 SignUpPage 구현
  jest.config.js
  package-lock.json
  package.json
  src/api/queries/useUser.ts
  src/api/user/index.ts
  src/components/AppBar.tsx
  src/components/common/Button/ButtonVariants.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/hooks/useImageInput.tsx
  src/hooks/useTextInput.tsx
  src/hooks/useViewportIntersection.tsx
  src/index.css
  src/mocks/handlers.ts
  src/pages/SignUpPage.tsx
  src/router/ProtectedRoute.tsx
  src/router/PublicOnlyRoute.tsx
  src/router/router.tsx
  src/utils/textValidators.test.ts
  src/utils/textValidators.ts
  tsconfig.json
Labels: feat, design

#45 Hot fix: Button props type 수정
  src/components/common/Button/ButtonVariants.tsx
Labels: fix
